"""phase 2 core schema

Revision ID: 57f0fe8dd206
Revises: 
Create Date: 2026-05-24 18:28:42.627334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f0fe8dd206'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=20)), server_default=sa.text("'{developer}'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_id'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('cost_centres',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('budget_cap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_cost_centres_status', 'cost_centres', ['status'], unique=False)
    op.create_table('global_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cost_centre_owners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cost_centre_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['cost_centres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cost_centre_id', 'user_id', name='uq_cost_centre_owners')
    )
    op.create_table('key_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('cost_centre_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('approved_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['cost_centres.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_requests_cost_centre', 'key_requests', ['cost_centre_id'], unique=False)
    op.create_index('idx_key_requests_developer', 'key_requests', ['developer_id'], unique=False)
    op.create_index('idx_key_requests_status', 'key_requests', ['status'], unique=False)
    op.create_table('keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('cost_centre_id', sa.UUID(), nullable=False),
    sa.Column('key_request_id', sa.UUID(), nullable=False),
    sa.Column('iam_username', sa.String(length=255), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('allowed_models', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('rolling_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rolling_period_days', sa.Integer(), nullable=True),
    sa.Column('lifetime_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lifetime_spend', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['cost_centres.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['key_request_id'], ['key_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('iam_username'),
    sa.UniqueConstraint('key_request_id')
    )
    op.create_index('idx_keys_cost_centre', 'keys', ['cost_centre_id'], unique=False)
    op.create_index('idx_keys_developer', 'keys', ['developer_id'], unique=False)
    op.create_index('idx_keys_status', 'keys', ['status'], unique=False)
    op.create_index('uq_keys_active_dev_cc', 'keys', ['developer_id', 'cost_centre_id'], unique=True, postgresql_where=sa.text("status IN ('active', 'stopped')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_keys_active_dev_cc', table_name='keys', postgresql_where=sa.text("status IN ('active', 'stopped')"))
    op.drop_index('idx_keys_status', table_name='keys')
    op.drop_index('idx_keys_developer', table_name='keys')
    op.drop_index('idx_keys_cost_centre', table_name='keys')
    op.drop_table('keys')
    op.drop_index('idx_key_requests_status', table_name='key_requests')
    op.drop_index('idx_key_requests_developer', table_name='key_requests')
    op.drop_index('idx_key_requests_cost_centre', table_name='key_requests')
    op.drop_table('key_requests')
    op.drop_table('cost_centre_owners')
    op.drop_table('global_settings')
    op.drop_index('idx_cost_centres_status', table_name='cost_centres')
    op.drop_table('cost_centres')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
